<?php  $_gridrecords = $block->getCollection(); // get collection which we set in block class ?>
<?php if ($_gridrecords && count($_gridrecords)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?php echo __('Grid Record') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?php echo __('ID #') ?></th>
                    <th scope="col" class="col title"><?php echo __('Name') ?></th>
                    <th scope="col" class="col date"><?php echo __('Date') ?></th>
                    <th scope="col" class="col status"><?php echo __('Biography') ?></th>
                    <th scope="col" class="col ">Edit</th>
                    <th scope="col" class="col ">Delete</th>
                </tr>
            </thead>
            <tbody>
                <?php  // read collection as magento1.x and display in list
                       foreach ($_gridrecords as $_gridrecord): ?>
                    <tr>
                        <td class="col id"><?php echo $_gridrecord['author_id']; ?></td>
                        <td class="col shipping"><?php echo $_gridrecord['name'];?></td>
                        <td class="col date"><?php echo $block->formatDate($_gridrecord['dob']) ?></td>
                        <td class="col status"><?php echo $_gridrecord['biography'];?></td>
                        <td class="col edit"></td>
                        <td class="col Delete"></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <!--<?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); // for display pager block which we create in block file.   ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('grid records not available.'); ?></span></div>
<?php endif ?>-->
