<?php  $_gridrecords = $block->getCollection(); // get collection which we set in block class 
$author = $_gridrecords->getData();
$name = isset($author['0']['name'])?$author['0']['name']:'';
$dob = isset($author['0']['dob'])?$author['0']['dob']:'';
$biography = isset($author['0']['biography'])?$author['0']['biography']:'';
$country = isset($author['0']['country'])?$author['0']['country']:'';
$author_id = isset($author['0']['author_id'])?$author['0']['author_id']:'';

?>
 <div class="table-wrapper orders-history">
 <FORM METHOD="POST" ACTION="<?php echo $this->getUrl('trial/index/index');?>">
<table class="data table table-order-items history" id="my-orders-table">
	<tr>
		<td scope="col" class="col title"><?php echo __('Name') ?></td>
		<td><input type="text" name="name" value="<?php echo $name; ?>" ></td>
	</tr>
	<tr>
		<td scope="col" class="col title"><?php echo __('Date') ?></td>
		<td><input type="text" name="dob" value="<?php echo $dob; ?>" ></td>
	</tr>
	<tr>
		<td scope="col" class="col title"><?php echo __('Biography') ?></td>
		<td><input type="text" name="biography" value="<?php echo $biography; ?>" ></td>
	</tr>
	<tr>
		<td scope="col" class="col title"><?php echo __('Country') ?></td>
		<td><input type="text" name="country" value="<?php echo $country; ?>" ></td>
	</tr>

	<tr>
		<td scope="col" class="col title" colspan="2">
			<input type="hidden" name="author_id" value="<?php echo $author_id; ?>" >
			<center><input type="submit" value="Submit" class="action submit primary"></center>
		</td>
		
	</tr>	
</table>
</FORM>
</div>